- name: Display AWS Information
  hosts: localhost
  gather_facts: True
  pre_tasks:
    - name: Get EC2 Remote Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "*_{{ aws_custom_prefix }}_*"
        region: "{{ aws_region }}"
      register: my_ec2_facts
    - include: aws_pretasks.yml
  vars:
    - ec2_instance_info: []
  roles:
    - aws_display_info
