- name: Create AWS Infrastructure
  hosts: localhost
  gather_facts: True
  pre_tasks:
    - include: aws_pretasks.yml
  roles:
    - aws_infrastructure
  tasks:
    - debug:
        msg:
          -  "EC2 Instance Tags:       Name={{ item.tags.Name }}"
          -  "EC2 Instance ID:         {{ item.id }}"
          -  "Region:                  {{ aws_region }}"
      with_items: "{{ ec2_instances.instances }}"
    - set_fact:
        msg: |
            EC2 Instance Tags:         Name={{ instance_name }}
            EC2 Instance ID:           {{ ec2_instances_id }}
            Associated to Elastic IP:  {{ elastic_ip.public_ip }}
            Hostname:                  {{ hostname }}
            DNS WildCard Entry:        {{ wildcard_entry }}
            SSH Key Name:              {{ ssh_key_name }}
            Region:                    {{ aws_region }}
    - set_fact:
        msg: "{{ msg }}

            Proxy EC2 Instance Tag:    Name={{ proxy_instance_name }}\n
            Proxy EC2 ID:              {{ proxy_ec2_instance_id }}\n
            Proxy Public IP:           {{ proxy_public_ip }}\n
            Proxy Private IP:          {{ proxy_private_ip }}\n
            On VPC Proxy URL:          http://{{ proxy_private_ip }}:3128"
      when: ec2_use_proxy
    - debug:
        msg: "{{ msg.split('\n') }}"
