- name: Terminate AWS EC2 Instance(s)
  hosts: localhost
  gather_facts: True
  pre_tasks:
    - include: aws_pretasks.yml
    - name: Get EC2 Remote Facts
      ec2_remote_facts:
        filters:
          instance-state-name: running
          "tag:Name": "*_{{ aws_custom_prefix }}_*"
        region: "{{ aws_region }}"
      register: my_ec2_facts
  vars:
    - deleted_ec2_instance_info: []
  roles:
    - aws_terminate_ec2_instances
